/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ceragir (https://sketchfab.com/ceragir)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ikea-storsint-martini-glass-c8b4d7a3bc164e129513c8e2b97e3567
Title: IKEA STORSINT  - Martini Glass
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { MartiniScene } from '../assets/images'

function MartiniGlass(props) {
  const { nodes, materials } = useGLTF(MartiniScene)
  return (
    <group {...props} dispose={null}>
      <group scale={1}>
        <mesh geometry={nodes.Prebake_1_cerise_0.geometry} material={materials.cerise} />
        <mesh geometry={nodes.Prebake_1_Champagne_0.geometry} material={materials.Champagne} />
        <mesh geometry={nodes.Prebake_1_Verre_0.geometry} material={materials.Verre} />
      </group>
    </group>
  )
}

useGLTF.preload(MartiniScene)
export default MartiniGlass