/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AR Neophyte (https://sketchfab.com/AR_Neophyte)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/martini-dry-3-olives-ea25a944c67e4a1a8f1fe07f15af2f7d
Title: Martini- dry-3 olives
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import MartiniGlass from '../assets/images/martini.glb';

function Martini(props) {
  const { nodes, materials } = useGLTF(MartiniGlass)
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Glass_Condensed_Glass_0.geometry}
        material={materials.Condensed_Glass}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube003_Oli001_0.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube003_Wood_0.geometry}
        material={materials.PaletteMaterial002}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cone__0.geometry}
        material={materials.Cone__0}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload(MartiniGlass)

export default Martini
