/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Rigsters (https://sketchfab.com/rigsters)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/young-satyr-drinking-wine-31eecd2b54964764aa343688404925c2
Title: Young Satyr drinking Wine
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { a } from '@react-spring/three'
import { useFrame } from '@react-three/fiber'
import SatyrScene from '../assets/images/satyr.glb';

const Satyr = (props) => {
  const groupRef = useRef(); // Referencia al grupo para aplicar rotación
  const { nodes, materials } = useGLTF(SatyrScene)

  // Rotación animada sobre el eje Y para que el modelo gire en su propio eje
  useFrame(() => {
    if (groupRef.current) {
      groupRef.current.rotation.y += 0.0001; // Gira suavemente sobre el eje Y
    }
  });

  return (
    <a.group ref={groupRef} {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials['default']}
        position={[0, 0, 0]} // Posición centrada
        rotation={[0, 0, -Math.PI]} // Mantén la rotación inicial en el eje Z
        scale={1.483} // Escala del modelo
      />
    </a.group>
  )
}

useGLTF.preload(SatyrScene)

export default Satyr;